### ISSUE TITLE
watcher get exit when file change

### ISSUE THREAD

**Issue by maxlibin** [melange-re/melange-opam-template#3]
Tried this template, run smoothly until make a change to a file will force watcher to exit immediately.

https://user-images.githubusercontent.com/1277038/199159481-6cc30f2d-4c6d-4060-8277-cbad477ad012.mp4

**Comment by jchavarri** [comment]
Thanks for checking the template and reporting the issue! I opened an issue upstream: https://github.com/melange-re/melange/issues/400.

Will add a workaround for the opam template in a new PR.
