### ISSUE TITLE
Schema for bsconfig doesn't allow for workspaces

### ISSUE THREAD

**Issue by mlms13** [melange-re/melange-opam-template#6]
The `bsconfig.json` included in this template uses a schema definition borrowed from the Rescript compiler:

https://github.com/melange-re/melange-opam-template/blob/main/bsconfig.json#L2

But as far as I'm aware, Rescript doesn't support multi-workspace projects, and Melange does with the help of a [`workspace` field (holding key-value pairs)](https://github.com/melange-re/melange/blob/main/jscomp/build_tests/monorepo/bsconfig.json#L14) in the bsconfig.

**Comment by jchavarri** [comment]
@mlms13 thanks for opening the issue.

We recently merged the changes to use `dune` files instead of `bsconfig.json`. As `dune` files supports multi-workspace configurations by default, I am going to close it, but please feel free to reopen if additional fixes are needed.
